#!/bin/bash
cd ./BitTorrent/_1001
javac -cp ../../ PeerProcess1001.java
cd ../_1002
javac -cp ../../ PeerProcess1002.java
cd ../_1003
javac -cp ../../ PeerProcess1003.java
cd ../_1004
javac -cp ../../ PeerProcess1004.java
cd ../_1005
javac -cp ../../ PeerProcess1005.java
cd ../_1006
javac -cp ../../ PeerProcess1006.java
cd ../_1007
javac -cp ../../ PeerProcess1007.java
cd ../_1008
javac -cp ../../ PeerProcess1008.java
cd ../_1009
javac -cp ../../ PeerProcess1009.java
